###############################################################################
# サーバの設定
###############################################################################
[server]
kind				= "tokio"

[tokio]
worker_threads		= 5
blocking_threads	= 50
keep_alive			= 60
stack_size			= 3145728
address				= "127.0.0.1"
port				= "8000"


###############################################################################
# アプリケーション設定
###############################################################################
[app]
app_name			= "xxx"
version				= "1.0.0"

[logger]
kind				= "tracing"


###############################################################################
# ロガーの設定
###############################################################################
[tracing]
log_level			= "trace"
logfile_path		= "./output/logs"
logfile_name		= "app_log"

